
order:
  addr: "localhost"
  port: 50053

product:
  addr: "localhost"
  port: 50052

auth:
  addr: "localhost"
  port: 50051

db:
  username: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5432
  dbname: "store"