name: e-commerce

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Verify dependencies
        run: go mod verify

      - name: Run vet & lint
        run: |
          go vet ./...
          golint ./...

      - name: Run test
        run: go test -v  ./...

      - name: Build
        run: go build -v cmd/store-gateway/main.go # pg conn needs for others


